// color-game-svelte/src/components/PlayerForm.svelte
<form on:submit|preventDefault={submit}>
    <div class="div-bloco"> 
        <Input 
            bind:value={p.playername} 
            on:input={e=> touched['playername']=true} 
            on:blur={e => checkField('playername')} 
            placeholder="Player name" 
            isRequired="true" 
            error={errors['playername']} 
        />
        <Input 
            bind:value={p.nickname} 
            on:input={e=> touched['nickname']=true} 
            on:blur={e => checkField('nickname')} 
            placeholder="Nick name" 
            isRequired="true" 
            error={errors['nickname']} 
        />
    </div>
    <div class="div-bloco"> 
        <Input 
            bind:value={p.birthday} 
            on:input={e=> touched['birthday']=true} 
            on:blur={e => checkField('birthday')} 
            placeholder="Birthday" 
            isRequired="true" 
            error={errors['birthday']} 
        />
        <Input 
            bind:value={p.email} 
            on:input={e=> touched['email']=true} 
            on:blur={e => checkField('email')} 
            placeholder="Email" 
            isRequired="true" 
            error={errors['email']} 
        />
    </div>
    <div class="time">
        <button class="difficulty-button buttonlevel" type="button" on:click={() => setLevel(12)}> EASY</button>
        <button class="difficulty-button buttonlevel" type="button" on:click={() => setLevel(8)}> MEDIUM</button>
        <button class="difficulty-button buttonlevel" type="button" on:click={() => setLevel(5)}> HARD</button>
    </div>
    <div class="div-bloco"> 
	    <button type="submit" class="colorful-button">Play</button>
    </div>
</form>

<script>
  import {
    minLengthValidation,
    requiredValidation
  } from './validations.js'
  
  import { createEventDispatcher } from 'svelte'
  
  import Input from './Input.svelte'

  export let player
  const validate = {
    playername: value => minLengthValidation(3, value),
    nickname: requiredValidation,
    birthday: requiredValidation,
    email: requiredValidation
  }

  let errors = {}
  let touched = {}
  const dispatch = createEventDispatcher()

  const { playername, nickname, birthday, email, level } = player || {}
  let p = {playername, nickname, birthday, email, level }

  function checkField(name) {
    errors[name] = ''
    if (validate[name] && touched[name]) {
      const value = p[name]
      errors[name] = validate[name](value) || ''
    }
  }

  function submit() {
    Object.keys(p).forEach(field => {
      touched[field] = true
      checkField(field)
    })
    const errorsIsEmpty = !Object.values(errors).some(v => v)
    if (errorsIsEmpty) {
    console.log("enviando de PlayerForm", p)
      dispatch('update', {
          playername: p.playername,
          nickname: p.nickname,
          birthday: p.birthday,
          email: p.email,
          level: p.level
      })
    }
  }

  function setLevel(value) {
    p.level = value
  }
</script>

// color-game-react/src/components/PlayerForm.js
import React from 'react'
import { requiredValidation, minLengthValidation } from '../forms/validations'
import '../assets/css/player-form.css';
import '../assets/css/game-style.css';

const validate = {
    playerName: (value) => minLengthValidation(3, value),
    nickname: requiredValidation,
    birthday: requiredValidation,
    email: requiredValidation
  }

export default class PlayerForm extends React.Component {
  constructor(props) {
    super(props)
    this.state = {
        playerName: '',
        nickname: '',
        birthday:'',
        email: '',
        errors: {},
        touched: {}
      
    }
    this.onChange = this.onChange.bind(this)
    this.onSubmit = this.onSubmit.bind(this)
    this.onBlur = this.onBlur.bind(this)
  }
  
  onChange(event) {
    const { name, value } = event.target
    this.setState((state) => ({
      ...state,
      [name]: value,
      touched: { ...state.touched, [name]: true }
    }))
  }

  onBlur(event) {
    const { name, value } = event.target
    const { [name]: removedError, ...rest } = this.state.errors
    const error = validate[name] ? validate[name](value) : null
    const errorValue = this.state.touched[name] ? error : null

    this.setState((state) => ({
      ...state,
      errors: {
        ...rest,
        [name]: errorValue
      }
    }))
  }

  onSubmit(event) {
    event.preventDefault()
    console.log(this.state)
  }


  render() {
    return (
        <div className="form">
            <form onSubmit={this.onSubmit}>
                <div>
                    <input name="playerName" value={this.state.playerName} placeholder="Name" onChange={this.onChange} onBlur={this.onBlur}/>
                    <input name="nickname" value={this.state.nickname} placeholder="Nickname" onChange={this.onChange} onBlur={this.onBlur}/>
                    <div className="error">{this.touched && this.errors.playerName}</div>
                </div>
                <div>
                    <input name="birthday" value={this.state.birthday} placeholder="Birthday" onChange={this.onChange} onBlur={this.onBlur}/>
                    <input name="email" value={this.state.email} placeholder="E-mail" onChange={this.onChange} onBlur={this.onBlur}/>
                </div>
                <div id="difficulty">
                            <button className="difficulty-button">EASY</button>
                            <button className="difficulty-button">MEDIUM</button>
                            <button className="difficulty-button">HARD</button>
                </div>
                <div >
                    <input id="submit" className="colorful-button" type="submit" value="Enviar" />
                </div>
            </form>
      </div>
    )
  }
}
