// color-game-angular/src/Components/Countdown/countdown.component.ts
import { Component } from '@angular/core'

@Component({
  selector: 'countdown',
  template: 
  `
    <div>         
        <h2 *ngIf="timerCount == 0" > GameOver {{timeIsOver()}} </h2>
        <h2 *ngElseIf="!addTime"> GameOver {{timeIsOver()}} </h2>
        <h2 *ngElse> Countdown: {{ timerCount }} </h2>
    </div>
  `
})

export class CountdowComponent {

    name: "Countdown"
    props: ["addTime"]
    
    timerCount : 5 

    timeIsOver() {
        console.log("O tempo acabou");
        return true;
    }

    countDownTimer() {
        if(this.timerCount > 0) {
            setTimeout(() => {
                this.timerCount -= 1
                this.countDownTimer()
            }, 1000)
        }
    }
    
    created() {
        this.countDownTimer()
    }
}

// color-game-vue/src/components/Countdown.vue
<template>
    <div>
        
        <h2 v-if = "timerCount == 0" > GameOver {{timeIsOver()}} </h2>
        <h2 v-else-if = "!addTime" > GameOver {{timeIsOver()}} </h2>
        <h2 v-else>Countdown: {{ timerCount }} </h2>
        
    </div>
</template>

<script>
export default {
    name: "Countdown",
    props: ["addTime"],
    data() {
            return {
                timerCount : 5
            }
    },
    methods: {
        timeIsOver: function() {
            console.log("O tempo acabou");
            this.$emit('timeIsOver', true);
        },
        countDownTimer() {
            if(this.timerCount > 0) {
                setTimeout(() => {
                    this.timerCount -= 1
                    this.countDownTimer()
                }, 1000)
            }
        },
    },
    created() {
        this.countDownTimer()
    }
}
</script>
