// color-game-react/src/components/Home.js
import React from 'react';
import Game from './Game';
import '../assets/css/game-style.css';
let time = 0;

class Home extends React.Component {

    state = {
        startGame: false,
    };


    startNewGame = (value) => {
        this.time = value;
        console.log(time)
        this.setState({
            startGame: true
        })
    }



    render() {
        //Constante que armazena o que será mostrado na tela, se o game continua ou se já acabou
        return (
            <div>

                {this.state.startGame ?
                    <Game
                        difficulty={this.time} />
                    :
                    <div>

                        <div>
                            <h1>The Stroop Effect Game</h1>
                        </div>
                        <div className="rowCard">
                            <div className="rowCard50">
                                <figure className="container-img">
                                    <section id="cerebro-image">
                                        <img src={require("../assets/images/cerebro.png")} alt="colored brain" />
                                    </section>
                                </figure>
                            </div>
                            <div className="rowCard50">
                                <div className="card">
                                    <div className="card-text">
                                        The Stroop effect is related to selective attention, which
                                        is the ability to respond to certain environmental stimuli
                                        while ignoring others.
                                        <br />
                                        <br />
                                        For example, when a word like
                                        <span style={{ color: 'red' }}> blue </span>,
                                        <span style={{ color: 'blue' }}> green </span>
                                        or
                                        <span style={{ color: 'green' }}> red </span>
                                        is printed in a color that differs from the color expressed
                                        by the meaning semantic, there is a delay in processing the
                                        word color, causing slower reaction times and an increase in
                                        errors.
                                        <br />
                                                            <br />
                                        Therefore, the stroop effect reveals the degree of
                                        time that people have to say the name of the color
                                        with which the word is painted, instead of the real word.
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div>
                            <button className="colorful-button" onClick={() => this.startNewGame(12)}>EASY</button>
                            <button className="colorful-button" onClick={() => this.startNewGame(8)}>MEDIUM</button>
                            <button className="colorful-button" onClick={() => this.startNewGame(5)}>HARD</button>
                        </div>                     
                        
                    </div>                  


                }
            </div>
        );
    }
}

export default Home;

// color-game-vue/src/components/Home.vue
<template>
    <div>
        <Game
        v-if="startGame"
        :difficulty="time"
        ></Game>
        <div v-else>            
            <div>
        <h1>The Stroop Effect Game</h1>
    </div>
    <div class="rowCard">
        <div class="rowCard50">
            <figure class="container-img">
                <section id="cerebro-image">
                    <img :src="require(`@/assets/images/cerebro.png`)" alt="colored brain" />
                </section>
            </figure>
        </div>
        <div class="rowCard50">
            <div class="card">
                <div class="card-text">
                    The Stroop effect is related to selective attention, which
                    is the ability to respond to certain environmental stimuli
                    while ignoring others.
                    <br />
                    <br />
                    For example, when a word like
                    <span style="color: red"> blue </span>,
                    <span style="color: blue"> green </span>
                    or
                    <span style="color: green"> red </span>
                    is printed in a color that differs from the color expressed
                    by the meaning semantic, there is a delay in processing the
                    word color, causing slower reaction times and an increase in
                    errors.
                    <br />
                    <br />
                    Therefore, the stroop effect reveals the degree of
                    time that people have to say the name of the color
                    with which the word is painted, instead of the real word.
                </div>
            </div>
        </div>
    </div>
    <div class="time">
        <button class="colorful-button" @click={startNewGame(12)}>EASY</button>
        <button class="colorful-button" @click={startNewGame(8)}>MEDIUM</button>
        <button class="colorful-button" @click={startNewGame(5)}>HARD</button>
    </div>
        </div>
    </div>
</template>

<script>
import Game from "./Game.vue";
export default {
  name: "Home",
  components: {
    Game,
  },
  data: () => {
    return {        
        startGame: false,
        time:0
    }

  },
  methods: {
      startNewGame(value) {
        this.time = value;
        console.log(this.time)
        this.startGame = true;
    }

  },
};
</script>

<style>
</style>
