// color-game-angular/src/Components/screen.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core'

@Component({
  selector: 'screen',
  template:
    `
    <h1 style="color: {{rightColor.colorNumber}}">{{options[0]}}</h1>
    <button class="colorful-button" *ngFor="let option of options; index as idx" (click)="userOption.emit(idx)">
      {{ option }}
    </button>
  `
})
export class ScreenComponent {
  @Input() options: object[];
  @Input() rightColor: object;
  @Output() userOption = new EventEmitter<number>();

}

// color-game-svelte/src/components/Screen.svelte
<script>
    export let options;
    export let rightColor;
    import { createEventDispatcher } from "svelte";

    const dispatch = createEventDispatcher();
</script>

<h1 style="color: {rightColor.colorNumber}">{options[0]}</h1>

{#each options as option, index (option)}
    <button class="colorful-button" on:click={dispatch('userOption', index)}>{option}</button>
{/each}
