// color-game-svelte/src/components/PlayerForm.svelte
<form on:submit|preventDefault={submit}>
    <div class="div-bloco"> 
        <Input 
            bind:value={p.playername} 
            on:input={e=> touched['playername']=true} 
            on:blur={e => checkField('playername')} 
            placeholder="Player name" 
            isRequired="true" 
            error={errors['playername']} 
        />
        <Input 
            bind:value={p.nickname} 
            on:input={e=> touched['nickname']=true} 
            on:blur={e => checkField('nickname')} 
            placeholder="Nick name" 
            isRequired="true" 
            error={errors['nickname']} 
        />
    </div>
    <div class="div-bloco"> 
        <Input 
            bind:value={p.birthday} 
            on:input={e=> touched['birthday']=true} 
            on:blur={e => checkField('birthday')} 
            placeholder="Birthday" 
            isRequired="true" 
            error={errors['birthday']} 
        />
        <Input 
            bind:value={p.email} 
            on:input={e=> touched['email']=true} 
            on:blur={e => checkField('email')} 
            placeholder="Email" 
            isRequired="true" 
            error={errors['email']} 
        />
    </div>
    <div class="time">
        <button class="colorful-button" class="buttonlevel" on:click={() => setLevel(12)}> EASY</button>
        <button class="colorful-button" class="buttonlevel" on:click={() => setLevel(8)}> MEDIUM</button>
        <button class="colorful-button" class="buttonlevel" on:click={() => setLevel(5)}> HARD</button>
    </div>
    <div class="div-bloco"> 
	    <input type="submit" value="Jogar">
    </div>
</form>

<script>
  import {
    minLengthValidation,
    requiredValidation
  } from './validations.js'
  
  import { createEventDispatcher } from 'svelte'
  
  import Input from './Input.svelte'

  export let player
  const validate = {
    playername: value => minLengthValidation(3, value),
    nickname: requiredValidation,
    birthday: requiredValidation,
    email: requiredValidation
  }

  let errors = {}
  let touched = {}
  const dispatch = createEventDispatcher()

  const { playername, nickname, birthday, email, level } = player || {}
  let p = {playername, nickname, birthday, email, level }

  function checkField(name) {
    errors[name] = ''
    if (validate[name] && touched[name]) {
      const value = p[name]
      errors[name] = validate[name](value) || ''
    }
  }

  function submit() {
    Object.keys(p).forEach(field => {
      touched[field] = true
      checkField(field)
    })
    const errorsIsEmpty = !Object.values(errors).some(v => v)
    if (errorsIsEmpty) {
    console.log("enviando de PlayerForm", p)
      dispatch('update', {
          playername: p.playername,
          nickname: p.nickname,
          birthday: p.birthday,
          email: p.email,
          level: p.level
      })
    }
  }

  function setLevel(value) {
    p.level = value
  }
</script>

// color-game-angular/src/app/Components/playerForm.component.ts
import { Component,Input, OnInit, Output, EventEmitter,  } from '@angular/core'

interface PlayerType {
    playername: string,
    nickname: string,
    birthday: string, 
    email: string,
    level: number
} 
@Component({
  selector: 'player-form',
  template:`   
        <form #playerForm="ngForm" (ngSubmit)="playerForm.form.valid && onSubmit()"  >
            <div class="div-bloco"> 
                <player-input
                    type="input"
                    placeholder="Player name"
                    isRequired="true"
                    minlength="3"
                    name="playername"
                    [(value)]="player.playername"
                ></player-input>

                <player-input
                    type="input"
                    placeholder="Nick name"
                    isRequired="true"
                    minlength="3"
                    name="nickname"
                    [(value)]="player.nickname"
                ></player-input>
            </div>     
            <div class="div-bloco"> 
                <player-input
                    type="input"
                    placeholder="Birthday 00/00/00"
                    isRequired="true"
                    minlength="3"
                    name="birthday"
                    [(value)]="player.birthday"
                > </player-input>  
                <player-input 
                    type="input"
                    placeholder="email"
                    minlength="3"
                    name="email"
                    [(value)]="player.email"
                > </player-input>
            </div>
            <div class="time" >
                <button class="colorful-button" (click)="addLevel(12)"> EASY</button>
                <button class="colorful-button" (click)="addLevel(8)"> MEDIUM</button>
                <button class="colorful-button" (click)="addLevel(5)"> HARD</button>
            </div>
            <div class="div-bloco"> 
                <input type="submit" class="submit" value="jogar"/>
            </div>
        </form> 
  `,
  
  styleUrls:['./player-form.component.css']

})

export class PlayerFormComponent {
    @Input() player: PlayerType
    @Output() send = new EventEmitter()
    
    addLevel(value) {
        this.player.level = value;
    }

    ngOnInit() {
        const {playername, nickname, birthday, email, level }  = this.player || {}
        
        this.player = {
          playername,
          nickname,
          birthday,
          email,
          level
        }
        console.log(level)



      }

    onSubmit() {

        if( this.player.playername === '' || 
            this.player.nickname === '' ||
            this.player.birthday === '' ||
            this.player.level === 0 ) {
                alert('NECESSÁRIO PREENCHER O FORMULÁRIO')
        } else {
            const obj = [
                this.player.playername,
                this.player.nickname,
                this.player.birthday,
                this.player.email,
                this.player.level
              ]
              console.log(obj)
              this.send.emit({
                 player: obj
              })
        }
    }
}
